image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "29"
  ANDROID_COMPILE_NDK: "21.3.6528147"
  ANDROID_TEST_SDK: "21"
  ANDROID_SDK_TOOLS: "6514223"
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive
  GOOGLE_PUBLISH_JSON: app/misc/android-publisher-account.json

.configure_android_sdk: &configure_android_sdk
  # download android cmdline tools
  - mkdir -pv android-sdk-linux
  - wget --quiet --output-document=android-cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}_latest.zip
  - unzip -q android-cmdline-tools.zip -d android-sdk-linux/cmdline-tools && rm -v android-cmdline-tools.zip
  # set environment variables
  - export ANDROID_HOME="$PWD/android-sdk-linux"
  - export PATH="$PATH:$ANDROID_HOME/cmdline-tools/tools/bin:$ANDROID_HOME/platform-tools"
  - export NDK_HOME=$ANDROID_HOME/ndk/$ANDROID_COMPILE_NDK
  # install required components
  - echo y | sdkmanager --install "platforms;android-${ANDROID_COMPILE_SDK}" > /dev/null
  - echo y | sdkmanager --install "platform-tools" > /dev/null
  - echo y | sdkmanager --install "extras;android;m2repository" > /dev/null
  - echo y | sdkmanager --install "extras;google;m2repository" > /dev/null
  - echo y | sdkmanager --install "ndk;${ANDROID_COMPILE_NDK}" > /dev/null

.configure_gradle: &configure_gradle
  - export GRADLE_USER_HOME=$PWD/.gradle
  - chmod +x ./gradlew

.install_rust_toolchain: &install_rust_toolchain |
  apt-get --quiet install gcc --yes
  curl -sSf https://sh.rustup.rs | sh -s -- -y
  source $HOME/.cargo/env
  rustup target add armv7-linux-androideabi
  rustup target add aarch64-linux-android
  rustup target add i686-linux-android
  rustup target add x86_64-linux-android


.compile_html2md: &compile_html2md |
  cd $CI_PROJECT_DIR
  ./html2md-build.sh


.decrypt_release_account: &decrypt_publish_json |
  apt-get --quiet install gnupg2 --yes
  gpg --batch --decrypt --output ${GOOGLE_PUBLISH_JSON} --passphrase ${GOOGLE_ACCOUNT_DECRYPTION_KEY} ${GOOGLE_PUBLISH_JSON}.gpg


before_script:
  - apt-get --quiet update --yes
  - *configure_android_sdk
  - *configure_gradle


cache:
  paths:
    # gradle cache
    - .gradle/caches/
    - .gradle/wrapper/
    # rust compiled deps
    - html2md/target


stages:
  - build
  - test
  - release


smoke-build:
  stage: build
  script:
    - *install_rust_toolchain
    - *compile_html2md
    - ./gradlew assembleRelease


release-alpha:
  stage: release
  except:
    - merge_requests
    - tags
  script:
    - *decrypt_publish_json
    - *install_rust_toolchain
    - *compile_html2md
    - ./gradlew app:publishGoogleplayRelease
  after_script:
    - rm -f ${GOOGLE_PUBLISH_JSON}
  artifacts:
    paths:
      - app/build/outputs/apk


release-gold:
  stage: release
  except:
    - merge_requests
  only:
    - tags
  script:
    - *decrypt_publish_json
    - *install_rust_toolchain
    - *compile_html2md
    - ./gradlew publishGoogleplayRelease -PreleaseType=production
  after_script:
    - rm -f ${GOOGLE_PUBLISH_JSON}
  artifacts:
    paths:
      - app/build/outputs/apk
